### ISSUE TITLE
simplewallet : opening wallet with letter O

### ISSUE THREAD

**Issue by citizenz7** [ParsiCoin/parsicoin#5]
Opening a wallet with letter "o" (small o) with simple wallet won't work as it generates a wallet instead.
You have to enter a "capital O" to open a wallet.

**Comment by ParsiCoin** [comment]
Fixed, Thanks.
https://github.com/ParsiCoin/parsicoin/commit/f0bd7bdd1b0d149090a5fdfa1a9d53217f33a0dd
