### ISSUE TITLE
Authorization required wallet rpc

### ISSUE THREAD

**Issue by yasaricli** [ParsiCoin/parsicoin#8]
Hello;

wallet is correct but I get the "Authorization required" error.

```
./walletd 
  --container-file=test 
  --container-password=test
  --generate-container
```

```
./walletd 
  --container-file=test.wallet 
  --container-password=test 
  --bind-address=0.0.0.0
  --bind-port=8070 
  --rpc-user=test 
  --rpc-password=test
```

### Response

    Authorization required

Thanks.

**Comment by ParsiCoin** [comment]
Hello , run with --rpc-legacy-security flag.

**Comment by yasaricli** [comment]
no not working.

```
./walletd --container-file=test --container-password=test --bind-address=0.0.0.0 --bind-port=8070 --rpc-user=test --rpc-password=test --daemon-address=127.0.0.1 --daemon-port=1303 --rpc-legacy-security
```

#### Curl Request

```
curl -s -u test:test -X POST http://127.0.0.1:8070/json_rpc -H 'Content-Type: application/json-rpc' -d '{"jsonrpc": "2.0", "id": "test", "method": "getAddresses", "params": { }}'
```

#### Response

```
2019-Feb-04 22:44:23.939920 WARNING Authorization required 127.0.0.1:56011
2019-Feb-04 22:44:40.577481 WARNING Authorization required 127.0.0.1:56011
```

**Comment by ParsiCoin** [comment]
it should not return that error when you are using --rpc-legacy-security flag we will take a look at the code to fix it , but it's also useless if server get compromised , so maybe we revert that auth type for the sake of services which are using our RPC Wallet.

**Comment by yasaricli** [comment]
I use the **--rpc-legacy-security** flag without a password, it works. But I don't use the flag if the user and the password are correct but the result **Authorization required**.


#### İts Works
```
./walletd --container-file=test --container-password=test --rpc-legacy-security
```

#### User password is correct but does not work.
```
./walletd --container-file=test --container-password=test --rpc-user=test --rpc-password=test
```

**Comment by yasaricli** [comment]
Problem solved. Thanks.
